const mongoose = require('mongoose');

/**
 * Goal Model
 * Represents a student's goal set for a particular date and curriculum phase.
 */
const goalSchema = new mongoose.Schema(
  {
    // Reference to the Student who created this goal
    studentId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Student',
      required: [true, 'Goal must be associated with a Student.'],
    },
    // Reference to the curriculum Phase that this goal corresponds to
    phaseId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Phase',
      required: [true, 'Goal must be linked to a Phase.'],
    },
    title: {
      type: String,
      required: [true, 'Goal title is required.'],
      trim: true,
    },
    description: {
      type: String,
      trim: true,
      default: '',
    },
    // The specific date targeted for the goal
    date: {
      type: Date,
      required: [true, 'Goal date is required.'],
      default: Date.now,
    },
    // Current status of the goal
    status: {
      type: String,
      required: [true, 'Goal status is required.'],
      enum: {
        values: ['Pending', 'In Progress', 'Completed', 'Missed'],
        message: '{VALUE} is not a valid goal status.',
      },
      default: 'Pending',
    },
    // Numeric value representing how close the goal is to completion (0 - 100)
    completionPercentage: {
      type: Number,
      required: true,
      default: 0,
      min: [0, 'Completion percentage cannot be less than 0.'],
      max: [100, 'Completion percentage cannot exceed 100.'],
    },
    // Numerical score (0-100) evaluated by the AI model
    aiScore: {
      type: Number,
      min: [0, 'AI score cannot be less than 0.'],
      max: [100, 'AI score cannot exceed 100.'],
      default: null,
    },
    // Summary feedback generated by the AI evaluating the goal definition/execution
    aiFeedback: {
      type: String,
      trim: true,
      default: '',
    },
    // Feedback left by a mentor/instructor on the student's goal progress
    mentorFeedback: {
      type: String,
      trim: true,
      default: '',
    },
  },
  {
    timestamps: true,
  }
);

// Compound index to speed up student progress queries
goalSchema.index({ studentId: 1, date: 1 });

const Goal = mongoose.model('Goal', goalSchema);

module.exports = Goal;
